// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace api.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220215085112_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Contrato", b =>
                {
                    b.Property<int>("idContrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("IdMisil")
                        .HasColumnType("int");

                    b.Property<int?>("frenteIdFrente")
                        .HasColumnType("int");

                    b.Property<int>("idFrente")
                        .HasColumnType("int");

                    b.Property<int?>("misilIdMisil")
                        .HasColumnType("int");

                    b.HasKey("idContrato");

                    b.HasIndex("frenteIdFrente");

                    b.HasIndex("misilIdMisil");

                    b.ToTable("contrato");
                });

            modelBuilder.Entity("Frente", b =>
                {
                    b.Property<int>("IdFrente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("FrenteIdFrente")
                        .HasColumnType("int");

                    b.Property<string>("Pais")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdFrente");

                    b.HasIndex("FrenteIdFrente");

                    b.ToTable("frente");
                });

            modelBuilder.Entity("Misil", b =>
                {
                    b.Property<int>("IdMisil")
                        .HasColumnType("int");

                    b.Property<float>("Megatones")
                        .HasColumnType("real");

                    b.Property<int?>("MisilIdMisil")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMisil");

                    b.HasIndex("MisilIdMisil");

                    b.ToTable("misil");
                });

            modelBuilder.Entity("Contrato", b =>
                {
                    b.HasOne("Frente", "frente")
                        .WithMany("Contratos")
                        .HasForeignKey("frenteIdFrente");

                    b.HasOne("Misil", "misil")
                        .WithMany("Contratos")
                        .HasForeignKey("misilIdMisil");

                    b.Navigation("frente");

                    b.Navigation("misil");
                });

            modelBuilder.Entity("Frente", b =>
                {
                    b.HasOne("Frente", null)
                        .WithMany("Frentes")
                        .HasForeignKey("FrenteIdFrente");
                });

            modelBuilder.Entity("Misil", b =>
                {
                    b.HasOne("Misil", null)
                        .WithMany("Misiles")
                        .HasForeignKey("MisilIdMisil");
                });

            modelBuilder.Entity("Frente", b =>
                {
                    b.Navigation("Contratos");

                    b.Navigation("Frentes");
                });

            modelBuilder.Entity("Misil", b =>
                {
                    b.Navigation("Contratos");

                    b.Navigation("Misiles");
                });
#pragma warning restore 612, 618
        }
    }
}
